In [2]:
import pandas as pd
import chemsource

import os
import sys

sys.path.append(os.path.abspath("../src"))
from harmonization import (
    harmonize_automated_classification,
    harmonize_manual_classification,
    retrieve_sankey_1_data,
    retrieve_sankey_2_data,
)

In [15]:
classified_drug_library_data_path = "../data/drug_library/validation_data_classified_all_3_methods.csv"

harmonized_automated = harmonize_automated_classification(classified_drug_library_data_path)
harmonized_manual = harmonize_manual_classification(classified_drug_library_data_path)


harmonized_automated_non_medical = harmonized_automated[harmonized_automated['GPT_RAG'].apply(lambda x: 'MEDICAL' not in x and "INFO" not in x)]
harmonized_automated_medical = harmonized_automated[harmonized_automated['GPT_RAG'].apply(lambda x: 'MEDICAL' in x and "INFO" not in x)]
harmonized_automated_info = harmonized_automated[harmonized_automated['GPT_RAG'].apply(lambda x: 'INFO' in x)]

In [ ]:
drug_library_text = pd.read_csv(classified_drug_library_data_path)
drug_library_text["FEATURE_ID"] = drug_library_text.index
drug_library_text = drug_library_text[["FEATURE_ID", 
    "name_used", 
    "text"]].rename(columns={
    "name_used": "NAME",
    "text": "TEXT"})

In [26]:
non_medical_random_sample_idx = harmonized_automated_non_medical.sample(n=50, 
    random_state=42).index.tolist()
medical_random_sample_idx = harmonized_automated_medical.sample(n=50, 
    random_state=42).index.tolist()
info_random_sample_idx = harmonized_automated_info.sample(n=50, 
    random_state=42).index.tolist()

non_medical_random_sample = drug_library_text.loc[non_medical_random_sample_idx]
medical_random_sample = drug_library_text.loc[medical_random_sample_idx]
info_random_sample = drug_library_text.loc[info_random_sample_idx]

In [27]:
non_medical_random_sample

,FEATURE_ID,NAME,TEXT
2352,2352,Solamargine,Solamargine is a cytotoxic chemical compound t...
1700,1700,Sulfanitran,Sulfanitran is a sulfonamide antibiotic which ...
1825,1825,Trans-piceid,Piceid is a stilbenoid glucoside and is a majo...
2498,2498,Butylhydroxytoluene,"Butylated hydroxytoluene (BHT), also known as ..."
1442,1442,Tricyclazole,"Tricyclazole (8-methyl-[1,2,4]triazolo[3,4-b]..."
3482,3482,Vanillate,Vanillic acid (4-hydroxy-3-methoxybenzoic acid...
56,56,Isoleucine,Isoleucine (symbol Ile or I) is an α-amino aci...
4453,4453,Alpha-linoleic acid,"α-Linolenic acid, also known as alpha-linoleni..."
4908,4908,Sodium taurolithocholate,The proportion of sodium taurolithocholate (N...
1297,1297,Isoascorbic acid,"Erythorbic acid (isoascorbic acid, D-araboasco..."
1551,1551,Arresten,Collagen alpha-3(IV) chain is a protein that i...
4944,4944,Methylpyrrolidone,N-Methyl-2-pyrrolidone (NMP) is an organic com...
1757,1757,Formylformic acid,Glyoxylic acid or oxoacetic acid is an organic...
1637,1637,Pantothenic acid,Pantothenic acid (vitamin B5) is a B vitamin a...
2424,2424,Ethanedioic acid,Oxalic acid is an organic acid with the system...
1703,1703,Isopentanoic acid,"Isovaleric acid, also known as 3-methylbutanoi..."
4926,4926,Lipid crimson,Sudan IV (C24H20N4O) is a lysochrome (fat-solu...
3099,3099,Isomalt,"Isomalt is a sugar substitute, a mixture of th..."
2745,2745,Spermin,Spermine is a polyamine involved in cellular m...
3314,3314,Trans-vaccenic acid,Vaccenic acid is a naturally occurring trans f...
163,163,Capstar,Nitenpyram is a chemical frequently used as an...
3669,3669,P-nitrophenyl phosphate,para-Nitrophenylphosphate (pNPP) is a non-prot...
3604,3604,N-acetylhistamine,N-Acetylhistamine administered to mice and ra...
3354,3354,Phloretol,"Phloretin is a dihydrochalcone, a type of natu..."
33,33,Hydroxyethanoic acid,Glycolic acid (or hydroxyacetic acid; chemical...
4754,4754,Curdlan,"Curdlan is a water-insoluble linear beta-1,3-g..."
4772,4772,Anilide,"In organic chemistry, anilides (or phenylamide..."
2124,2124,Lysine,Lysine (symbol Lys or K) is an α-amino acid th...
1744,1744,Xylite,Xylitol is a chemical compound with the formul...
2286,2286,Urocaninic acid,Urocanic acid (formally trans-Urocanic acid) i...
4060,4060,Chloromethylisothiazolinone,"Methylchloroisothiazolinone, also referred to ..."
3326,3326,Maltotetraose,Maltodextrin is a name shared by two different...
4332,4332,Liquorice,Liquorice (Commonwealth English) or licorice (...
4925,4925,Secoisolariciresinol,Secoisolariciresinol is an organic compound. I...
2083,2083,Dihydroxyphenylethanol,Hydroxytyrosol is an organic compound with the...
2418,2418,Chitosamine,Glucosamine (C6H13NO5) is an amino sugar and a...
2125,2125,Butanedioic acid,Succinic acid () is a dicarboxylic acid with t...
1456,1456,Bornan-2-one,"Camphor () is a waxy, colorless solid with a s..."
1407,1407,Uridine monophosphate,"Uridine monophosphate (UMP), also known as 5′-..."
4816,4816,Octyl methoxycinnamate,Octyl methoxycinnamate or ethylhexyl methoxyci...
1472,1472,Benzophenone-3,Oxybenzone or benzophenone-3 or BP-3 (trade na...
1817,1817,Uridine diphosphoglucose,Uridine diphosphate glucose (uracil-diphosphat...
1118,1118,Isopropyl myristate,Isopropyl myristate (IPM) is the ester of isop...
1418,1418,Acetic acid amide,Acetamide (systematic name: ethanamide) is an ...
1401,1401,Aminoethanoic acid,Glycine (symbol Gly or G; ) is an amino acid t...
3295,3295,Galangin flavanone,"Chrysin, also called 5,7-dihydroxyflavone, is ..."
102,102,Tryptamine,Tryptamine is an indolamine metabolite of the ...
3202,3202,Tetradecanoic acid,Myristic acid (IUPAC name: tetradecanoic acid)...
4669,4669,"N,n'-diphenyl-p-phenylenediamine",A 28-day repeated dose toxicity test and repr...
1396,1396,Hyodesoxycholic acid,"Hyodeoxycholic acid, also known as 3α,6α-Dihyd..."

In [19]:
pd.read_csv(classified_drug_library_data_path)

,synonyms,manual_classification,text,name_used,site,chemsource_output_gpt-4o,chemsource_output_deepseek-v3,chemsource_output_gpt-4-1,chemsource_output_search_gpt
0,('(s)-2-(6-(4-chlorophenyl)-8-methoxy-1-methyl...,Medical,The bromodomain and extraterminal (BET) prote...,I-bet762,PUBMED,"('MEDICAL', [('MED', -7.941850526549388e-06), ...","('MEDICAL', [('MED', -0.03046262077987194), ('...","('MEDICAL', [('MED', -1.1472419600977446e-06),...",('INFO; ([cellsignal.com](https://www.cellsign...
1,"('Molibresib', 'I-bet762', 'I-bet-762', 'I-bet...",Medical,"Molibresib is a selective, small molecule inh...",Molibresib,PUBMED,"('MEDICAL', [('MED', -3.128163257315464e-07), ...","('MEDICAL', [('MED', -0.00010644822759786621),...","('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])",('MEDICAL; ([pubmed.ncbi.nlm.nih.gov](https://...
2,"('Elenbecestat', 'N-[3-[(4as,5r,7as)-2-amino-5...",Medical,Many factors contribute to inadequate diversi...,Elenbecestat,PUBMED,"('MEDICAL', [('MED', -1.6240566083070007e-06),...","('MEDICAL', [('MED', -0.006801193580031395), (...","('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])",('INFO; https://www.nasdaq.com/press-release/e...
3,"('Dianhydrodulcitol', 'Dianhydrogalactitol', '...",Medical,The effect of dianhydrodulcithol (DAD) admini...,Dianhydrodulcitol,PUBMED,"('MEDICAL', [('MED', -0.10020806640386581), ('...","('MEDICAL', [('MED', -0.050965193659067154), (...","('MEDICAL', [('MED', -0.06429484486579895), ('...",('INFO; https://www.selleckchem.com/products/d...
4,"('Erlotinib', 'N-(3-ethynylphenyl)-6,7-bis(2-m...",Medical,"Erlotinib, sold under the brand name Tarceva a...",Erlotinib,WIKIPEDIA,"('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])","('MEDICAL', [('MED', -7.510157047363464e-06), ...","('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])",('MEDICAL; https://en.wikipedia.org/wiki/Erlot...
...,...,...,...,...,...,...,...,...,...
4948,"('Telenzepine', 'Telenzepine hydrochloride', '...",Medical,Telenzepine is a thienobenzodiazepine acting a...,Telenzepine,WIKIPEDIA,"('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])","('MEDICAL', [('MED', -0.00023600654094479978),...","('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])",('INFO; ([en.wikipedia.org](https://en.wikiped...
4949,"('Gal', 'Galactopyranose', 'Galactopyranoside'...","Endogenous, Medical","Galactose (, galacto- + -ose, ""milk sugar""), s...",Galactose,WIKIPEDIA,"('ENDOGENOUS, FOOD', [('END', -0.1272564977407...","('FOOD, ENDOGENOUS', [('FO', -0.06912534683942...","('ENDOGENOUS, FOOD', [('END', -0.0005531519418...","('ENDOGENOUS, FOOD; https://en.wikipedia.org/w..."
4950,"('Mephedrone', 'Meow meow', 'M-cat', 'Bubbles'...",Medical,"Mephedrone, also known as 4-methylmethcathinon...",Mephedrone,WIKIPEDIA,"('INDUSTRIAL', [('IND', -0.25217655301094055),...","('INDUSTRIAL, MEDICAL', [('IN', -0.05683630332...","('INDUSTRIAL', [('IND', -0.25283879041671753),...",('INDUSTRIAL; https://en.wikipedia.org/wiki/Me...
4951,"('Norbuprenorphine', 'Des(cyclopropylmethyl)bu...",Drug metabolite,Norbuprenorphine is a major active metabolite ...,Norbuprenorphine,WIKIPEDIA,"('ENDOGENOUS', [('END', -0.9052175879478455), ...","('MEDICAL, ENDOGENOUS', [('MED', -0.0032858450...","('INFO', [('INFO', -0.575939953327179)])",('INFO; https://en.wikipedia.org/wiki/Norbupre...
4952,"('Muscimol', 'Agarin', 'Pantherine', 'Agarine'...",Medical,Muscimol (also known as agarin or pantherine) ...,Pantherine,WIKIPEDIA,"('FOOD, INFO', [('FO', -0.7657619714736938), (...","('MEDICAL, FOOD, INFO', [('MED', -0.4975584745...","('INFO', [('INFO', 0.0)])","('INFO; ', [])"

In [13]:
pd.read_csv(classified_drug_library_data_path)

,synonyms,manual_classification,text,name_used,site,chemsource_output_gpt-4o,chemsource_output_deepseek-v3,chemsource_output_gpt-4-1,chemsource_output_search_gpt
0,('(s)-2-(6-(4-chlorophenyl)-8-methoxy-1-methyl...,Medical,The bromodomain and extraterminal (BET) prote...,I-bet762,PUBMED,"('MEDICAL', [('MED', -7.941850526549388e-06), ...","('MEDICAL', [('MED', -0.03046262077987194), ('...","('MEDICAL', [('MED', -1.1472419600977446e-06),...",('INFO; ([cellsignal.com](https://www.cellsign...
1,"('Molibresib', 'I-bet762', 'I-bet-762', 'I-bet...",Medical,"Molibresib is a selective, small molecule inh...",Molibresib,PUBMED,"('MEDICAL', [('MED', -3.128163257315464e-07), ...","('MEDICAL', [('MED', -0.00010644822759786621),...","('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])",('MEDICAL; ([pubmed.ncbi.nlm.nih.gov](https://...
2,"('Elenbecestat', 'N-[3-[(4as,5r,7as)-2-amino-5...",Medical,Many factors contribute to inadequate diversi...,Elenbecestat,PUBMED,"('MEDICAL', [('MED', -1.6240566083070007e-06),...","('MEDICAL', [('MED', -0.006801193580031395), (...","('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])",('INFO; https://www.nasdaq.com/press-release/e...
3,"('Dianhydrodulcitol', 'Dianhydrogalactitol', '...",Medical,The effect of dianhydrodulcithol (DAD) admini...,Dianhydrodulcitol,PUBMED,"('MEDICAL', [('MED', -0.10020806640386581), ('...","('MEDICAL', [('MED', -0.050965193659067154), (...","('MEDICAL', [('MED', -0.06429484486579895), ('...",('INFO; https://www.selleckchem.com/products/d...
4,"('Erlotinib', 'N-(3-ethynylphenyl)-6,7-bis(2-m...",Medical,"Erlotinib, sold under the brand name Tarceva a...",Erlotinib,WIKIPEDIA,"('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])","('MEDICAL', [('MED', -7.510157047363464e-06), ...","('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])",('MEDICAL; https://en.wikipedia.org/wiki/Erlot...
...,...,...,...,...,...,...,...,...,...
4948,"('Telenzepine', 'Telenzepine hydrochloride', '...",Medical,Telenzepine is a thienobenzodiazepine acting a...,Telenzepine,WIKIPEDIA,"('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])","('MEDICAL', [('MED', -0.00023600654094479978),...","('MEDICAL', [('MED', 0.0), ('ICAL', 0.0)])",('INFO; ([en.wikipedia.org](https://en.wikiped...
4949,"('Gal', 'Galactopyranose', 'Galactopyranoside'...","Endogenous, Medical","Galactose (, galacto- + -ose, ""milk sugar""), s...",Galactose,WIKIPEDIA,"('ENDOGENOUS, FOOD', [('END', -0.1272564977407...","('FOOD, ENDOGENOUS', [('FO', -0.06912534683942...","('ENDOGENOUS, FOOD', [('END', -0.0005531519418...","('ENDOGENOUS, FOOD; https://en.wikipedia.org/w..."
4950,"('Mephedrone', 'Meow meow', 'M-cat', 'Bubbles'...",Medical,"Mephedrone, also known as 4-methylmethcathinon...",Mephedrone,WIKIPEDIA,"('INDUSTRIAL', [('IND', -0.25217655301094055),...","('INDUSTRIAL, MEDICAL', [('IN', -0.05683630332...","('INDUSTRIAL', [('IND', -0.25283879041671753),...",('INDUSTRIAL; https://en.wikipedia.org/wiki/Me...
4951,"('Norbuprenorphine', 'Des(cyclopropylmethyl)bu...",Drug metabolite,Norbuprenorphine is a major active metabolite ...,Norbuprenorphine,WIKIPEDIA,"('ENDOGENOUS', [('END', -0.9052175879478455), ...","('MEDICAL, ENDOGENOUS', [('MED', -0.0032858450...","('INFO', [('INFO', -0.575939953327179)])",('INFO; https://en.wikipedia.org/wiki/Norbupre...
4952,"('Muscimol', 'Agarin', 'Pantherine', 'Agarine'...",Medical,Muscimol (also known as agarin or pantherine) ...,Pantherine,WIKIPEDIA,"('FOOD, INFO', [('FO', -0.7657619714736938), (...","('MEDICAL, FOOD, INFO', [('MED', -0.4975584745...","('INFO', [('INFO', 0.0)])","('INFO; ', [])"

In [11]:
harmonized_automated_non_medical

,FEATURE_ID,SOURCE,DEEPSEEK_RAG,GPT_NO_RAG,GPT_RAG,SEARCH_GPT
8,8,PUBMED,[INFO],[INFO],[INFO],[INFO]
11,11,PUBMED,[INFO],[MEDICAL],[INFO],[MEDICAL]
12,12,WIKIPEDIA,[ENDOGENOUS],[ENDOGENOUS],[ENDOGENOUS],[ENDOGENOUS]
14,14,WIKIPEDIA,[INFO],[INDUSTRIAL],[INFO],[INFO]
28,28,WIKIPEDIA,[ENDOGENOUS],[ENDOGENOUS],[ENDOGENOUS],[ENDOGENOUS]
...,...,...,...,...,...,...
4946,4946,WIKIPEDIA,[INFO],[FOOD],[INFO],[INFO]
4949,4949,WIKIPEDIA,"[FOOD, ENDOGENOUS]","[ENDOGENOUS, FOOD]","[ENDOGENOUS, FOOD]","[ENDOGENOUS, FOOD]"
4950,4950,WIKIPEDIA,"[INDUSTRIAL, MEDICAL]",[INDUSTRIAL],[INDUSTRIAL],[INDUSTRIAL]
4951,4951,WIKIPEDIA,"[MEDICAL, ENDOGENOUS]",[INFO],[ENDOGENOUS],[INFO]
4952,4952,WIKIPEDIA,"[MEDICAL, FOOD, INFO]",[INFO],"[FOOD, INFO]",[INFO]